<a href="https://colab.research.google.com/github/siddharth10-dev/data-viz-python/blob/main/DAY_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("ecommerce_data.csv")

To download your file from Google Colab, you can use one of the following methods:

1.  **Using the File Browser (Graphical Interface)**:
    *   Click on the folder icon on the left sidebar of your Colab notebook to open the file browser.
    *   Navigate to the file you wish to download.
    *   Right-click on the file name.
    *   Select 'Download' from the context menu.

2.  **Using Python Code (Programmatic Download)**:
    You can also use the `google.colab.files` module to download files programmatically. For example, to download a file named `my_file.csv`:

    ```python
    from google.colab import files

    # Assuming 'df' is your DataFrame that you want to save to 'my_file.csv'
    # df.to_csv('my_file.csv', index=False)

    files.download('my_file.csv')
    ```

    Replace `'my_file.csv'` with the actual name of the file you want to download.

In [ ]:
from google.colab import files

# Save the DataFrame to a CSV file
df.to_csv('ecommerce_data_cleaned.csv', index=False)

# Download the file
files.download('ecommerce_data_cleaned.csv')

In [ ]:
df

,Order_ID,Date,Customer_Name,Product_Category,Price,Quantity,Discount_Pct,Payment_Method
0,1001,2023-10-17,Ivan,electronics,193.52,1,10.0,NaN
1,1002,2023-07-02,Grace,Beauty,475.85,1,5.0,NaN
2,1003,2023-06-28,Heidi,Beauty,368.68,1,10.0,PayPal
3,1004,2023-12-22,David,Electronics,303.34,5,5.0,PayPal
4,1005,2023-08-15,Ivan,Clothing,86.45,4,10.0,Credit Card
...,...,...,...,...,...,...,...,...
495,1496,2023-08-23,David,Electronics,183.14,2,NaN,Debit Card
496,1497,2023-04-27,Eve,Books,295.99,2,NaN,PayPal
497,1498,2023-10-08,Grace,Electronics,48.09,1,0.0,Credit Card
498,1499,2023-01-28,Grace,Books,487.45,5,0.0,Cash
499,1500,2023-11-16,Eve,CLOTHING,493.24,4,NaN,NaN

In [ ]:
df.head()

,Order_ID,Date,Customer_Name,Product_Category,Price,Quantity,Discount_Pct,Payment_Method
0,1001,2023-10-17,Ivan,electronics,193.52,1,10.0,NaN
1,1002,2023-07-02,Grace,Beauty,475.85,1,5.0,NaN
2,1003,2023-06-28,Heidi,Beauty,368.68,1,10.0,PayPal
3,1004,2023-12-22,David,Electronics,303.34,5,5.0,PayPal
4,1005,2023-08-15,Ivan,Clothing,86.45,4,10.0,Credit Card

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          500 non-null    int64
 1   Date              500 non-null    object
 2   Customer_Name     500 non-null    object
 3   Product_Category  500 non-null    object
 4   Price             500 non-null    float64
 5   Quantity          500 non-null    int64
 6   Discount_Pct      401 non-null    float64
 7   Payment_Method    392 non-null    object
dtypes: float64(2), int64(2), object(4)
memory usage: 31.4+ KB

In [ ]:
df['Discount_Pct'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
495     True
496     True
497    False
498    False
499     True
Name: Discount_Pct, Length: 500, dtype: bool

In [ ]:
null_discount_count = df['Discount_Pct'].isnull().sum()

In [ ]:
null_discount_count

np.int64(99)

In [ ]:
null_payment_methods=df['Payment_Method'].isnull().sum()

In [ ]:
null_payment_methods

np.int64(108)

In [ ]:
df['Product_Category']=df['Product_Category'].str.strip().str.title()

In [ ]:
df['Product_Category']

0      Electronics
1           Beauty
2           Beauty
3      Electronics
4         Clothing
          ...
495    Electronics
496          Books
497    Electronics
498          Books
499       Clothing
Name: Product_Category, Length: 500, dtype: object

In [ ]:
df['Discount_Pct'].fillna(0)

0      10.0
1       5.0
2      10.0
3       5.0
4      10.0
       ...
495     0.0
496     0.0
497     0.0
498     0.0
499     0.0
Name: Discount_Pct, Length: 500, dtype: float64

In [ ]:
df['Payment_Method'].fillna('Unknown')
df

,Order_ID,Date,Customer_Name,Product_Category,Price,Quantity,Discount_Pct,Payment_Method
0,1001,2023-10-17,Ivan,Electronics,193.52,1,10.0,NaN
1,1002,2023-07-02,Grace,Beauty,475.85,1,5.0,NaN
2,1003,2023-06-28,Heidi,Beauty,368.68,1,10.0,PayPal
3,1004,2023-12-22,David,Electronics,303.34,5,5.0,PayPal
4,1005,2023-08-15,Ivan,Clothing,86.45,4,10.0,Credit Card
...,...,...,...,...,...,...,...,...
495,1496,2023-08-23,David,Electronics,183.14,2,NaN,Debit Card
496,1497,2023-04-27,Eve,Books,295.99,2,NaN,PayPal
497,1498,2023-10-08,Grace,Electronics,48.09,1,0.0,Credit Card
498,1499,2023-01-28,Grace,Books,487.45,5,0.0,Cash
499,1500,2023-11-16,Eve,Clothing,493.24,4,NaN,NaN

In [ ]:
df['Total_Before_Discount']=df['Price']*df['Quantity']

In [ ]:
df['Total_Before_Discount']

0       193.52
1       475.85
2       368.68
3      1516.70
4       345.80
        ...
495     366.28
496     591.98
497      48.09
498    2437.25
499    1972.96
Name: Total_Before_Discount, Length: 500, dtype: float64

In [ ]:
df['Final_Price']=df['Total_Before_Discount']*(1-df['Discount_Pct']/100)

In [ ]:
df['Final_Price']

0       174.1680
1       452.0575
2       331.8120
3      1440.8650
4       311.2200
         ...
495          NaN
496          NaN
497      48.0900
498    2437.2500
499          NaN
Name: Final_Price, Length: 500, dtype: float64

In [ ]:
df['Discount_Pct'].fillna(0)

0      10.0
1       5.0
2      10.0
3       5.0
4      10.0
       ...
495     0.0
496     0.0
497     0.0
498     0.0
499     0.0
Name: Discount_Pct, Length: 500, dtype: float64

In [ ]:
df['Date']=pd.to_datetime(df['Date'])

In [ ]:
df['Date']

0     2023-10-17
1     2023-07-02
2     2023-06-28
3     2023-12-22
4     2023-08-15
         ...
495   2023-08-23
496   2023-04-27
497   2023-10-08
498   2023-01-28
499   2023-11-16
Name: Date, Length: 500, dtype: datetime64[ns]

In [ ]:
df['Discount_Pct'] = df['Discount_Pct'].fillna(0)
display(df['Discount_Pct'].isnull().sum())

np.int64(0)

In [ ]:
df['Final_Price'] = df['Total_Before_Discount'] * (1 - df['Discount_Pct'] / 100)
display(df['Final_Price'].head())

0     174.1680
1     452.0575
2     331.8120
3    1440.8650
4     311.2200
Name: Final_Price, dtype: float64

In [ ]:
total_revenue_by_category = df.groupby('Product_Category')['Final_Price'].sum().reset_index()
highest_revenue_category = total_revenue_by_category.loc[total_revenue_by_category['Final_Price'].idxmax()]
display(highest_revenue_category)

Product_Category    Electronics
Final_Price           84609.769
Name: 3, dtype: object

In [ ]:
total_price=df.groupby('Customer_Name')['Price'].sum().reset_index()

In [ ]:
top_3_customers = total_price.sort_values(by='Price', ascending=False).head(3)
display(top_3_customers)

  Customer_Name     Price
1           Bob  17001.47
6         Grace  13837.71
7         Heidi  13686.42

In [ ]:
most_popular_payment_method = df['Payment_Method'].value_counts()
display(most_popular_payment_method)

Payment_Method
Debit Card     118
PayPal          96
Cash            90
Credit Card     88
Name: count, dtype: int64

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month_name()

In [ ]:
df['Month'].value_counts()

Month
December     50
May          47
January      46
October      44
July         44
November     43
June         41
August       40
April        39
September    38
March        36
February     32
Name: count, dtype: int64

In [ ]:
df['Price_Category'] = df['Price'].apply(lambda x: 'Premium' if x > 300 else ('Mid-Range' if x > 100 else 'Budget'))
display(df.head())

,Order_ID,Date,Customer_Name,Product_Category,Price,Quantity,Discount_Pct,Payment_Method,Total_Before_Discount,Final_Price,Month,Price_Category
0,1001,2023-10-17,Ivan,Electronics,193.52,1,10.0,NaN,193.52,174.1680,October,Mid-Range
1,1002,2023-07-02,Grace,Beauty,475.85,1,5.0,NaN,475.85,452.0575,July,Premium
2,1003,2023-06-28,Heidi,Beauty,368.68,1,10.0,PayPal,368.68,331.8120,June,Premium
3,1004,2023-12-22,David,Electronics,303.34,5,5.0,PayPal,1516.70,1440.8650,December,Premium
4,1005,2023-08-15,Ivan,Clothing,86.45,4,10.0,Credit Card,345.80,311.2200,August,Budget

In [ ]:
df.groupby(['Product_Category','Payment_Method'])['Final_Price'].sum()

Product_Category  Payment_Method
Beauty            Cash               9287.2335
                  Credit Card        8919.7690
                  Debit Card         9137.9350
                  PayPal             7816.0455
Books             Cash              13234.9365
                  Credit Card       12305.8800
                  Debit Card        11278.9905
                  PayPal             5808.5520
Clothing          Cash              12961.9315
                  Credit Card       12471.2495
                  Debit Card        19259.0880
                  PayPal            11214.5710
Electronics       Cash               8392.3995
                  Credit Card       14234.3940
                  Debit Card        14864.4075
                  PayPal            11309.0570
Home & Kitchen    Cash               6888.7245
                  Credit Card        8440.0085
                  Debit Card        16169.1545
                  PayPal             6516.1270
Name: Final_Price, dtype: float64

In [ ]:
df.pivot_table(values='Final_Price',index='Month',columns='Product_Category',aggfunc='sum')

Product_Category,Beauty,Books,Clothing,Electronics,Home & Kitchen
Month,,,,,
April,664.8815,3594.8695,4702.8450,4509.8870,2364.9500
August,3934.8735,5722.0270,7835.6215,6048.3190,1744.0220
December,5038.2375,5813.5220,4580.5340,14142.2720,4622.2920
February,1313.1610,1892.4360,5597.3765,5215.1485,2091.5945
January,1818.0900,11475.7240,6034.6725,3501.1940,3312.0795
July,2925.4205,3282.2485,3839.7825,2878.1745,5226.1840
June,4149.9720,2657.3755,2985.8645,909.1985,5482.6460
March,5540.3010,4786.5780,5286.5980,3244.5115,4950.5735
May,4537.5680,5013.4550,8189.5455,4006.4715,5155.6325
November,5558.8815,2061.5380,5747.4045,9672.7110,6829.8380
October,3920.7950,2871.6750,7333.4170,6918.6685,3459.5245
September,4115.7240,4445.3950,3910.4535,3059.1630,5184.9695

In [ ]:
df.pivot_table(values='Quantity',index='Month',columns='Product_Category',aggfunc='sum')

Product_Category  Beauty  Books  Clothing  Electronics  Home & Kitchen
Month
April                 13     15        33           25              24
August                22     24        30           33              13
December              30     31        36           45              20
February               9      7        31           27              22
January                8     38        28           29              21
July                  24     24        23           23              22
June                  27     22        26           20              30
March                 22     23        27           24              20
May                   17     14        31           45              28
November              23     13        25           41              28
October               23     15        35           31              23
September             23     22        17           20              34

In [ ]:
top_product=df.groupby('Product_Category')['Quantity'].sum().head(1)

In [ ]:
top_product

Product_Category
Beauty    241
Name: Quantity, dtype: int64

In [ ]:
top_product_price=df.groupby('Product_Category')['Price'].sum().head(1)

In [ ]:
top_product_price

Product_Category
Beauty    21403.97
Name: Price, dtype: float64

In [ ]:
electronics_df = df[df['Product_Category']=='Electronics']
Customer_Electronics = electronics_df.groupby('Customer_Name')['Final_Price'].sum().sort_values(ascending=False).head(1)

In [ ]:
Customer_Electronics

Customer_Name
Bob    12317.2965
Name: Final_Price, dtype: float64

In [ ]:
import pandas as pd

locations_data = {
    'Customer_Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'City': ['New York', 'London', 'Mumbai', 'Paris', 'Berlin', 'Tokyo', 'Sydney', 'Dubai', 'Singapore', 'Toronto']
}
City = pd.DataFrame(locations_data)

display(City.head())

  Customer_Name      City
0         Alice  New York
1           Bob    London
2       Charlie    Mumbai
3         David     Paris
4           Eve    Berlin

In [ ]:
City

  Customer_Name       City
0         Alice   New York
1           Bob     London
2       Charlie     Mumbai
3         David      Paris
4           Eve     Berlin
5         Frank      Tokyo
6         Grace     Sydney
7         Heidi      Dubai
8          Ivan  Singapore
9          Judy    Toronto

In [ ]:
Merge=pd.merge(df,df_locations,on='Customer_Name')

In [ ]:
Merge

,Order_ID,Date,Customer_Name,Product_Category,Price,Quantity,Discount_Pct,Payment_Method,Total_Before_Discount,Final_Price,Month,Price_Category,City
0,1001,2023-10-17,Ivan,Electronics,193.52,1,10.0,NaN,193.52,174.1680,October,Mid-Range,Singapore
1,1002,2023-07-02,Grace,Beauty,475.85,1,5.0,NaN,475.85,452.0575,July,Premium,Sydney
2,1003,2023-06-28,Heidi,Beauty,368.68,1,10.0,PayPal,368.68,331.8120,June,Premium,Dubai
3,1004,2023-12-22,David,Electronics,303.34,5,5.0,PayPal,1516.70,1440.8650,December,Premium,Paris
4,1005,2023-08-15,Ivan,Clothing,86.45,4,10.0,Credit Card,345.80,311.2200,August,Budget,Singapore
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1496,2023-08-23,David,Electronics,183.14,2,NaN,Debit Card,366.28,NaN,August,Mid-Range,Paris
496,1497,2023-04-27,Eve,Books,295.99,2,NaN,PayPal,591.98,NaN,April,Mid-Range,Berlin
497,1498,2023-10-08,Grace,Electronics,48.09,1,0.0,Credit Card,48.09,48.0900,October,Budget,Sydney
498,1499,2023-01-28,Grace,Books,487.45,5,0.0,Cash,2437.25,2437.2500,January,Premium,Sydney
499,1500,2023-11-16,Eve,Clothing,493.24,4,NaN,NaN,1972.96,NaN,November,Premium,Berlin

In [ ]:
Most_revenue=Merge.groupby('City')['Final_Price'].sum().sort_values(ascending=False).head(1)

In [ ]:
Most_revenue

City
London    34484.868
Name: Final_Price, dtype: float64